### PR TITLE
Move theme options to a custom sphinx theme

### PR DESCRIPTION
**Pull request by Maetveis**
As part of making rocm-docs-core a sphinx extension, move its theming settings to a sphinx theme `rocm_docs_theme`. This makes it easier to re-use. Also, the theme files no longer need to be copied to the documentation directory keeping things a little tidier.

This change is transparent to users because `setup()` sets the sphinx theme to this new bundled theme.

### CODE REVIEW

**Review by samjwu — APPROVED** [review]

**Comment by lawruble13** [comment]
This looks excellent to me, I do have one question about the `setup` function in `__init__.py`, that should still be run correctly, yes? It includes a javascript file that is necessary for cookie compliance. Additionally I'd just like to confirm my understanding: there would now be 2 ways to use rocm-docs-core, 1) by using the current method (which would automatically set up `rocm_docs.theme`), or 2) by using `rocm_docs.theme` directly, is that accurate?

**Comment by Maetveis** [comment]
> This looks excellent to me, I do have one question about the `setup` function in `__init__.py`, that should still be run correctly, yes? 

Yes, since this PR doesn't move all settings to the new theme only the "theming related" ones, like the custom templates css, logos etc. I have not moved the favicon setting or the one that disables the sphinx logo, as they are not strictly `html_theme_options`, but they could be included as visual options.

> It includes a javascript file that is necessary for cookie compliance.

I think I should move that one over.

> Additionally I'd just like to confirm my understanding: there would now be 2 ways to use rocm-docs-core, 1) by using the current method (which would automatically set up `rocm_docs.theme`), or 2) by using `rocm_docs.theme` directly, is that accurate?

Yes, partly. The idea would be to split the current method to several sphinx extensions, the first of which is this theme, users that only need the theme are now able to specify `html_theme=rocm_docs_theme` in their `conf.py`. Another extension could be made for running doxygen (and doxysphinx, enabling breathe etc), and probably a miscellaneous one for everything else (e.g. external-toc, notfound pages, myst) would remain the `rocm_docs` extension.  

Backwards compatibility can be kept by making the current method enable these new extensions and setting their settings, and finally that can be dropped at a later time requiring users to instead specify the extensions they want to use.

**Comment by lawruble13** [comment]
@Maetveis This caused the following error when building on ReadTheDocs: `ImportError: cannot import name '_get_theme_options' from 'pydata_sphinx_theme'`

**Comment by Maetveis** [comment]
> @Maetveis This caused the following error when building on ReadTheDocs: `ImportError: cannot import name '_get_theme_options' from 'pydata_sphinx_theme'`

Ah, this is seems like it popped up since I last built this :sweat: , it looks like its this: issue https://github.com/pydata/pydata-sphinx-theme/issues/1274.

I'll see if the suggested solution there works for us. It might require regenerating the lock-files (requirements.txt) however.

**Comment by Maetveis** [comment]
I wonder how that even happened when supposedly we have our packages pinned in every repository.

**Comment by lawruble13** [comment]
> I wonder how that even happened when supposedly we have our packages pinned in every repository.

rocm-docs-core itself is not pinned, as it was changing quite often for a time and during early development it was convenient to not have it pinned, which may have contributed?. However we've reached the point where we should be pinning rocm-docs-core versions.

**Pull request merged**
