### PR TITLE
Update theming to comply with AMD standards

### PR DESCRIPTION
**Pull request by lawruble13**

### CODE REVIEW

**Review by samjwu — APPROVED** [review]
looks good to me. commitizen will complain if all commit messages are not prepended with one of the types here: https://rocm.docs.amd.com/projects/rocm-docs-core/en/latest/developer_guide/commitizen.html

**Comment by saadrahim** [comment]
Please amend the commits and force push

**Comment by saadrahim** [comment]
The height of the headers seems to big. See https://ir.amd.com/news-events/press-releases/detail/1115/amd-reports-fourth-quarter-and-full-year-2022-financial at 100% zoom and compare.

**Comment by saadrahim** [comment]
Not sure about the links on the headers.

**Pull request merged**
