### PR TITLE
Add fieldlist and replacements MyST extension

### PR DESCRIPTION
**Pull request by Naraenda**
Enables two MyST extensions:
- [`replacements`](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#typography) converts `(tm) (c)` to `™ ©`.
- [`fieldlist`](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#field-lists) is more visually pleasing than using tables to document command arguments.

### CODE REVIEW

**Comment by Naraenda** [comment]
It would be nice if we could get the ROCmCC CLI documentation in the same visual style as [LLVM/Clang's](https://clang.llvm.org/docs/UsersManual.html#command-line-options)

**Review by saadrahim — APPROVED** [review]

**Review by samjwu — APPROVED** [review]

**Review by lawruble13 — APPROVED** [review]

**Comment by lawruble13** [comment]
Does anything additional need to be added to the project requirements (e.g. additional pip packages)?

**Comment by Naraenda** [comment]
All dependencies are already required by Myst-Parser if I'm not mistaken. I can verify tomorrow.

**Comment by Naraenda** [comment]
I can confirm it works without installing any extra dependencies ^^

**Pull request merged**
