### PR TITLE
External intersphinx and project mapping in TOC

### PR DESCRIPTION
**Pull request by Maetveis**
- Intersphinx mappings are loaded from `projects.yaml` in this repository's develop branch. This file is also installed with rocm-docs-core, but will only be used if loading the remote file fails.
The idea with `projects.yaml` is that it will also store the information to map between the versioning schemes of the different libraries.

- Rewrite toc parsing to support `${<variable>}` stlye references and implement `${project:<projectname>}` to substitute the intersphinx base url.

### CODE REVIEW

**Review by samjwu — APPROVED** [review]

**Comment by saadrahim** [comment]
> * Intersphinx mappings are loaded from `projects.yaml` in this repository's develop branch. This file is also installed with rocm-docs-core, but will only be used if loading the remote file fails.
>   The idea with `projects.yaml` is that it will also store the information to map between the versioning schemes of the different libraries.
> * Rewrite toc parsing to support `${<variable>}` stlye references and implement `${project:<projectname>}` to substitute the intersphinx base url.

I think we should not pull from the develop branch. It is best to use it from the installed package. Using remote links is frowned upon by some of our customers using airgapped networks.

**Comment by Maetveis** [comment]
> I think we should not pull from the develop branch. It is best to use it from the installed package. Using remote links is frowned upon by some of our customers using airgapped networks.

For air-gapped systems just using the bundled version **is the current behavior** (since the download will fail and the fallback activates), so the suggestion would only impact systems that do have internet access (like our CI). Sphinx itself has to download its inventory from the intersphinx target URLs, so without modification (changing the inventory links to local copies) intersphinx won't work on air-gapped systems anyways.

The motivation behind this approach is that it gives us a faster reaction time if URLs change outside of our control (e.g. we currently have intersphinx mappings to python and sphinx). Pulling from the repository only a rebuild is needed to follow these changes, otherwise it would require bumping the rocm-docs-core version. This can be difficult on builds for past releases (e.g. we might have made breaking changes to rocm-docs-core since the build).

However I did realize one possible issue with the current approach: pull requests currently wouldn't test `projects.yaml` as they will use the version from `develop`. It makes it possible to introduce a broken  `projects.yaml` with the CI passing, which will then cause all new builds of dependant projects to fail.

**Comment by saadrahim** [comment]
@lawruble13 can you please take a look at this

**Review by samjwu — APPROVED** [review]
> Projects should be defined in projects.yaml and should set which key
> they correspond their by setting `external_projects_current_project`
> to this key.
> 
> I.e. given this `projects.yaml`
> ```yaml
> projects:
>   python: https://docs.python.org/3/
>   rtd: https://docs.readthedocs.io/en/stable/
>   sphinx: https://www.sphinx-doc.org/en/master/
>   rocm-docs-core: [https://rocm.docs.amd.com/projects/rocm-docs-core/en/${version}](https://rocm.docs.amd.com/projects/rocm-docs-core/en/$%7Bversion%7D)
> ```
> 
> conf.py from rocm-docs-core should contain:
> ```python3
> external_projects_current_project = "rocm-docs-core"
> ```
> 
> Adds support for specifying the "development" branch for each project
> defined in projects.yaml, this is achieved by setting the
> `development_branch` key for the project I.e.:
> 
> ```yaml
> projects:
>   ...
>   project:
>     target: <target-url>
>     development_branch: master
> ```
> 
> With this the mapping between projects is changed to the following
> 
> - Development branches map between each-other,
>   i.e. links on the "develop" branch of project A point to the "master"
>   branch of project "B" and vice-versa if A has set its
>   "development branch" to develop and B sets it to "master".
> 
> - Symbolic versions "latest" and "stable" map to themselves in other
>   projects
> 
> - Any other branch maps to "latest"

------------------------------------------------------------------------------------------

This commit message is very helpful for using these settings. I wonder if we should add a user guide in the docs pages.

**Pull request merged**
