### PR TITLE
ci(linting.yml): add markdown link checks

### PR DESCRIPTION
**Pull request by samjwu**
uses https://github.com/gaurav-nelson/github-action-markdown-link-check (Github action for https://github.com/tcort/markdown-link-check)

closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/393

### CODE REVIEW

**Comment by samjwu** [comment]
```
      with:
        folder-path: 'docs'
```

checks docs folder only

**Comment by saadrahim** [comment]
I will be really excited if it does work. Will it cause false positives? What's the safest way to deploy it? Can you check the README.md file as well?

**Comment by samjwu** [comment]
Tested this in https://github.com/RadeonOpenCompute/ROCm/pull/2456

There are a few problems, though much less than the sphinx linkcheck from https://docs.readthedocs.io/en/stable/build-customization.html#perform-a-check-for-broken-links

I would say the biggest issue is that it is not compatible with MyST cross-references. In particular, implicit links: https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#explicit-vs-implicit-link-text

**Comment by saadrahim** [comment]
> Tested this in [RadeonOpenCompute/ROCm#2456](https://github.com/RadeonOpenCompute/ROCm/pull/2456)
> 
> There are a few problems, though much less than the sphinx linkcheck from https://docs.readthedocs.io/en/stable/build-customization.html#perform-a-check-for-broken-links
> 
> I would say the biggest issue is that it is not compatible with MyST cross-references. In particular, implicit links: https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#explicit-vs-implicit-link-text

@LisaDelaney and @samjwu more reason to drop using myst cross references so we can use this tool.

**Comment by samjwu** [comment]
@saadrahim thoughts on this?

**Pull request closed without merging**
