### PR TITLE
Include fonts for AMD styling

### PR DESCRIPTION
**Pull request by lawruble13**

### CODE REVIEW

**Review by saadrahim — APPROVED** [review]
This is extraordinarily exciting. Merge ASAP.

**Comment by lawruble13** [comment]
Currently experiencing issues checking out rocm-docs-core on ReadTheDocs due to the private submodule, I'm investigating how we can resolve this.

**Comment by saadrahim** [comment]
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#machine-users

**Review by samjwu — APPROVED** [review]
https://rocmdocs.amd.com/projects/alpha/en/rtd/

header looks good

**Comment by saadrahim** [comment]
Merge! Merge! Merge!

**Pull request merged**
