### PR TITLE
Article info

### LINKED ISSUE #96: Add way to differentiate Windows and Linux documentation
Some documentation is meant for Linux or Windows users only.

To convey that clearly, a way is needed to indicate that.

Consider Windows and Linux icons on pages or selectively removing pages using a toggle.

### LINKED ISSUE #108: Add article info on each page
https://sphinx-design.readthedocs.io/en/latest/additional.html

Article info author can be the supported OS, Windows, Linux, Windows and Linux.

Use font awesome pro for win/lin icons

### PR DESCRIPTION
**Pull request by samjwu**
Provide the output directory (default is `_build/html`) and a list of pages to add an article info header to indicate whether the page is supported on Linux, Windows, or both

Example of how the config is used: https://github.com/RadeonOpenCompute/ROCm/compare/develop...samjwu:ROCm:lin-win

closes #96 
closes #108 

image

image

### CODE REVIEW

**Comment by saadrahim** [comment]
Include 
The author, date, and read-time options are parsed as syntax, so you can use substitutions like:

date

MyST: :date: "{sub-ref}`today`"

RST: :data: |today|

read-time

MyST: :read-time: "{sub-ref}`wordcount-minutes` min read"

**Comment by saadrahim** [comment]
Also, no need to state OS support. The icons will state that.
Also, the article info should be after the level 1 heading

**Comment by saadrahim** [comment]
I would reduce the font size if possible

**Comment by saadrahim** [comment]
Overall, this is exciting. I can't believe we are this far.

**Comment by samjwu** [comment]
image

[feat: allow substitutions for author, date, and read time in article …](https://github.com/RadeonOpenCompute/rocm-docs-core/pull/132/commits/0751d414d3e702e8d9788bd13ce22f114771167f)
[0751d41](https://github.com/RadeonOpenCompute/rocm-docs-core/pull/132/commits/0751d414d3e702e8d9788bd13ce22f114771167f)

also reduces article-info.html to single component for all OS and places article info below h1 header

**Comment by saadrahim** [comment]
We don't need author

**Comment by saadrahim** [comment]
And date is a year, can't we get the month and day

**Comment by saadrahim** [comment]
OS: Penguin Windows, Should we add OS: to it?

**Comment by samjwu** [comment]
> OS: Penguin Windows, Should we add OS: to it?

Done.
image

For author, date, read time, since it's a string substitution, the writer can include more information as desired in `conf.py`. (example above has no author and full date. based on https://github.com/RadeonOpenCompute/ROCm/compare/develop...samjwu:ROCm:lin-win)

**Comment by saadrahim** [comment]
Is there a better way to set this on all pages? Looks like https://github.com/RadeonOpenCompute/ROCm/compare/develop...samjwu:ROCm:lin-win some work involved with this. Can we go default Windows and Linux, and override on certain pages? 

Have a way in conf.py to set Linux or Windows for the entire project (think RCCL or HIP-VS)?

**Comment by samjwu** [comment]
[b2dfb75](https://github.com/RadeonOpenCompute/rocm-docs-core/pull/132/commits/b2dfb755c8af4dbc02b2e383f0cf82c1f6d971fd)

final solution: allow both a broad default and specific settings

i.e.: 
`setting_all_article_info = True` will make all pages have Linux, with broad settings set via `all_article_info...` variables

setting values in `article_pages` will apply specific settings to those, which are exclusive with the broad settings in `all_article_info...`

Example: https://github.com/RadeonOpenCompute/ROCm/compare/develop...samjwu:ROCm:lin-win

**Review by saadrahim — APPROVED** [review]

**Pull request merged**
